# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: c
env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.3
 - GHCVER=8.0.1

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - unset CC
install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libcwiid-dev
 - travis_retry sudo apt-get install cabal-install-1.24 ghc-$GHCVER-prof ghc-$GHCVER-dyn alex-3.1.4 happy-1.19.5
 - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.24/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
 - travis_retry cabal update

script:
 - travis_retry cabal install --run-tests -v -j1

notifications:
 email: true

branches:
    only:
          - master
          - develop

# deploy:
#   provider: hackage
#   username: keera_studios_ci
#   password:
#     secure: LedfSXrzHa4ZR4A0Tybx3RrdEaTuMCEV2iZ4tTwyx6BuMZ9kI++ezw6Ws2LPERaEFCWP5Qln+PcMlsNCaxepDSh5AnLD/kj7TK8reGulSMjDbjxKeNd5pIUYSKhZJIECw+hGqN3IX7XVFHhSKVyScMjCfhPnka+SjeNlKSKp9Ho4rYYqhjaFIb4L8GLMRseMoE3EWuvyi9EkX8Q11aDqS+o23SLLw8F/A3Gz2uSAXfjkWOjKo1ECkGUxwcrIG9i7zsTKBBR4j5slBneuqBE+YnC35FxSnhO3udPE9PRWV1NJxMYLFb0KaS0Ba3k99LGdVbMKjgbMGvpbnxx1NhUBO/SudTZO/XXV0GoP7sZ2Zzq7Yrw5zkbnWwBwGYEy7KMWIuq034scD4mxOlCiM0nB//0nUJ6ygktaoF/5c75dS/Hlwci3q+Tzc8/y8HdLGgk8MHpb9AzZLzURd5d0WzjgKNvploSDd/eiXWEJLKg59Ev+34G8OYJxOb9es5WxjZxIuT0xOcNkvGPzniP5MqJAfhAGoofYGyityb1VlrRLQgk6MpQFb0dAYIf5oaZAhbGqDzuPrrbaSQBm0Er5DW+/0ih4frOKuq+ERew/7uQcLogHgUfyB4ECrfJQ2JnPzfB3VM5G7p0tTl1DN10r6JW2f4XsLRwAZVgOXnoNtOAgZdE=
#   on:
#     branch: master
#     condition: "$GHCVER = 8.0.1"
